### ISSUE TITLE
Error after installing in mediawiki 1.37

### ISSUE THREAD

**Issue by Conhaque** [ProfessionalWiki/SimpleBatchUpload#49]
### Setup

- MW version:
- PHP version:
- DB (MySQL etc.):
- SBL version:
- Browser version:

### Issue

Im trying to install SimpleBatchUpload, after download and put the extension in the /extensions and put the line in LocalSettings wfLoadExtension( 'SimpleBatchUpload' );, im getting an error in mine mediawiki.

The error

Fatal error: Uncaught Exception: Unable to open file C:\xampp\htdocs\mediawiki/extensions/SimpleBatchUpload/extension.json: filemtime(): stat failed for C:\xampp\htdocs\mediawiki/extensions/SimpleBatchUpload/extension.json in C:\xampp\htdocs\mediawiki\includes\registration\ExtensionRegistry.php:182 Stack trace: #0 C:\xampp\htdocs\mediawiki\includes\GlobalFunctions.php(52): ExtensionRegistry->queue('C:\\xampp\\htdocs...') #1 C:\xampp\htdocs\mediawiki\LocalSettings.php(192): wfLoadExtension('SimpleBatchUplo...') #2 C:\xampp\htdocs\mediawiki\includes\Setup.php(145): require_once('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\mediawiki\includes\WebStart.php(90): require_once('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\mediawiki\index.php(44): require('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\mediawiki\includes\registration\ExtensionRegistry.php on line 182

I already tried in another mediawiki versions but get the same error

**Comment by Conhaque** [comment]
After install with Composer i get the following error:

Fatal error: Uncaught Error: SimpleBatchUpload\SimpleBatchUpload::registerEarlyConfiguration(): Argument #1 ($targetConfiguration) cannot be passed by reference in C:\xampp\htdocs\mediawiki\extensions\SimpleBatchUpload\src\SimpleBatchUpload.php:42 Stack trace: #0 C:\xampp\htdocs\mediawiki\includes\registration\ExtensionRegistry.php(574): SimpleBatchUpload\SimpleBatchUpload::initCallback(Array) #1 C:\xampp\htdocs\mediawiki\includes\registration\ExtensionRegistry.php(258): ExtensionRegistry->exportExtractedData(Array) #2 C:\xampp\htdocs\mediawiki\includes\Setup.php(168): ExtensionRegistry->loadFromQueue() #3 C:\xampp\htdocs\mediawiki\includes\WebStart.php(90): require_once('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\mediawiki\index.php(44): require('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\mediawiki\extensions\SimpleBatchUpload\src\SimpleBatchUpload.php on line 42

**Comment by JeroenDeDauw** [comment]
What PHP version?

**Comment by Conhaque** [comment]
> What PHP version?

8.14

**Comment by JeroenDeDauw** [comment]
8.1.4?

SimpleBatchUpload and some other extensions do not support 8.1 or later. MediaWiki also does not support it officially.

**Comment by Conhaque** [comment]
> 8.1.4?
> 
> SimpleBatchUpload and some other extensions do not support 8.1 or later. MediaWiki also does not support it officially.

here the version, So what i need to do ? downgrade mine php version?

![Screenshot_1](https://user-images.githubusercontent.com/52429506/162951768-87a0dc38-5780-46a2-bb88-89a2a7addacc.png)
![Screenshot_2](https://user-images.githubusercontent.com/52429506/162951769-04bb18e0-1faa-48a3-b78b-88357cc878bd.png)

**Comment by JeroenDeDauw** [comment]
yes

**Comment by Conhaque** [comment]
> yes

Any version recomendattion ?

**Comment by JeroenDeDauw** [comment]
7.4
